---
# file: roles/cloudman_image/defaults/cloudman.yml
#
#   Variables used during the image build process

# Controls which tasks are included, in case you want to execute/update
# only certain parts of the role.
cm_install_packages: yes
cm_install_libraries: yes
cm_add_system_users: yes
cm_venvburrito: yes
cm_system_environment: yes  # Also requires cm_venvburrito to be set
cm_install_s3fs: yes
cm_configure_nginx: yes
cm_install_proftpd: yes
cm_install_novnc: yes
cleanup: no
# If only_cleanup is set, only the cleanup tasks will run and no other.
# This is intended to be set as a command line variable.
only_cleanup: no

# System user details
galaxy_user_uid: 1001
default_user: ubuntu
default_user_home: /home/ubuntu

# CloudMan details
cm_hg_repo: https://bitbucket.org/galaxy/cloudman/raw/tip

# Details about additional software being installed
s3fs_version: 1.77
proftpd_package_url: https://s3.amazonaws.com/cloudman/galaxy-proftpd-1.3.5_gxycm-20140910b01-trusty_amd64.deb
nginx_package_url: https://s3.amazonaws.com/cloudman/galaxy-nginx-1.4.7_gxycm-20140902b01-trusty_amd64.deb
nginx_upload_store_path: /mnt/galaxy/upload_store

# novnc setup details
novnc_install_dir: /opt/galaxy/novnc
vnc_user: ubuntu
vnc_display: 1
vnc_depth: 16
vnc_geometry: 1024x768
