---
# Defaults for setting up Galaxy for CloudMan

# Control-flow variables
cm_setup_galaxy: yes

# Configuration options
cmg_setup_files:
  - src: galaxy/welcome.html
    dest: "{{ galaxy_server_dir }}/static/welcome.html"
  - src: galaxy/cloud.gif
    dest: "{{ galaxy_server_dir }}/static/images/cloud.gif"
  - src: galaxy/cloud_text.png
    dest: "{{ galaxy_server_dir }}/static/images/cloud_text.png"
  - src: galaxy/job_conf.xml.cloud
    dest: "{{ galaxy_server_dir }}/config/job_conf.xml"

# Extra, user defined files to copy, with src and dest properties
cmg_extra_files: []

galaxy_user_name: galaxy
galaxyFS_base_dir: /mnt/galaxy
galaxy_server_dir: "{{ galaxyFS_base_dir }}/galaxy-app"
galaxy_venv_dir: "{{ galaxy_server_dir }}/.venv"
galaxy_config_file: "{{ galaxy_server_dir }}/config/galaxy.ini"
