---
galaxy_info:
  author: The Galaxy Project
  description: Build a base CloudMan image (https://wiki.galaxyproject.org/CloudMan/)
  company: The Galaxy Project
  license: MIT
  min_ansible_version: 1.6
  platforms:
  - name: Ubuntu
    versions:
    - trusty
  categories:
  - system
  - cloud
  - clustering
dependencies:
  - { role: smola.java, java_packages: 'oracle-java7-installer' }
  - { role: galaxyprojectdotorg.galaxy-os, galaxy_user_uid: 1001}
