---
# Install and configure novnc
#  *Note* that VNC does not work - current status is captured here:
#  http://forum.odroid.com/viewtopic.php?f=77&t=5616

- name: Create novnc install dir {{ novnc_install_dir }}
  file: path={{ novnc_install_dir }} state=directory

- name: Clone novnc
  git: repo=https://github.com/kanaka/noVNC.git dest={{ novnc_install_dir }}

- name: Create ~/.vnc dir
  file: path=~/.vnc state=directory
  sudo_user: "{{ default_user }}"

- name: Remove old vncpasswd dir
  file: path=~/vncpasswd state=absent
  sudo_user: "{{ default_user }}"

- name: Clone vncpasswd
  git: repo=https://github.com/trinitronx/vncpasswd.py dest=~/vncpasswd
  sudo_user: "{{ default_user }}"

- name: Create vnc password bridge
  command: python ~/vncpasswd/vncpasswd.py {{ vnc_password }} -f ~/.vnc/passwd
  sudo_user: "{{ default_user }}"
  when: vnc_password is defined

- name: Chmod on vnc password file
  file: path=~/.vnc/passwd mode=0600
  sudo_user: "{{ default_user }}"
  when: vnc_password is defined

  # Move vnc_auto.html which takes vnc_password as query argument
  # to index.html and rewrite it so that password is autoset, no
  # need to specify via query parameter.
- name: Autoset novnc passwd to match the vnc one
  shell: sed 's/password\ =/password\ = "{{ vnc_password }}";\/\//' {{ novnc_install_dir }}/vnc_auto.html > {{ novnc_install_dir }}/index.html #"

- name: Remove temp vncpasswd dir
  file: path=~/vncpasswd state=absent
  sudo_user: "{{ default_user }}"

- name: Copy script for starting X
  copy: src=xstartup dest=~/.vnc/xstartup mode=0755
  sudo_user: "{{ default_user }}"

- name: Make sure /etc/X11/xinit/xinitrc has execute permissions set
  file: path=/etc/X11/xinit/xinitrc mode=0755

- name: Copy novnc init file
  copy: src=novnc_init dest=/etc/init.d/novnc mode=0755

- name: Copy novnc default file
  template: src=novnc_default.j2 dest=/etc/default/novnc

- name: Copy vncserver init file
  copy: src=vncserver_init dest=/etc/init.d/vncserver mode=0755

- name: Copy vncserver default file
  template: src=vncserver_default.j2 dest=/etc/default/vncserver

- include: create_simple_service.yml src_file='novnc'

- include: create_simple_service.yml src_file='vncserver'
