---
# Cleanup the image before bundling

- name: Don't autostart Apache at boot
  shell: /usr/sbin/update-rc.d -f apache2 remove
  ignore_errors: yes

- name: Remove unwanted packages
  apt: pkg={{ item }} state=absent
  with_items:
    - tntnet
    - tntnet-runtime
    - libtntnet9
    - vsftpd
    - supervisor

- name: Clean apt cache to recover some disk space
  shell: apt-get clean
  sudo: yes
  sudo_user: root

- name: Stop RabbitMQ server
  shell: "{{ item }}"
  with_items:
    - /etc/init.d/rabbitmq-server stop
    - service rabbitmq-server stop

- name: Delete unwanted files
  shell: rm -rf {{ item }}
  with_items:
    - /var/lib/rabbitmq/mnesia
    - /mnesia
    - /usr/bin/cm_autorun.log
    - "{{ default_user_home }}/.bash_history"
    - /etc/supervisor/supervisord.conf
  ignore_errors: yes

- name: Place a custom history file into the default_user's home dir
  copy: src=bash_history dest=~/.bash_history mode=0600
  sudo_user: "{{ default_user }}"

  # Note that no ssh logins will be possible after this task runs!
  # Hence, must execute all the required deletions as a single command
- name: Delete ssh login files
  shell: rm -f /etc/ssh/ssh_host_* /root/.ssh/authorized_keys* "{{ default_user_home }}/.ssh/authorized_keys*"
