---
#   Build the base machine image
#

- include: packages.yml
  when: cm_install_packages and not only_cleanup|bool

- include: install_venvburrito.yml username='galaxy' user_home='/home/galaxy'
  when: cm_venvburrito and not only_cleanup|bool

- include: install_venvburrito.yml username='{{ default_user }}' user_home='{{ default_user_home }}'  #'
  when: cm_venvburrito and not only_cleanup|bool

- include: system_environment.yml
  when: cm_system_environment and cm_venvburrito and not only_cleanup|bool

- include: system_tools.yml
  when: cm_system_tools and not only_cleanup|bool

- include: docker.yml
  when: cm_docker and not only_cleanup|bool

- include: s3fs.yml
  when: cm_install_s3fs and not only_cleanup|bool

- include: nginx.yml
  when: cm_configure_nginx and not only_cleanup|bool

- include: proftpd.yml
  when: cm_install_proftpd and not only_cleanup|bool

- include: novnc.yml
  when: cm_install_novnc and not only_cleanup|bool

- include: mpi_install.yml
  when: cm_install_mpi and not only_cleanup|bool

- include: r_packages.yml
  when: cm_install_r_packages and not only_cleanup|bool

- include: cleanup.yml
  when: cleanup|bool or only_cleanup|bool
