---
# Install system packages

- name: Add Cloudera repository
  get_url:
    url=http://archive.cloudera.com/cm5/ubuntu/trusty/amd64/cm/cloudera.list
    dest=/etc/apt/sources.list.d/cloudera_trusty.list

- name: Add line to apt sources.list for R version upgrade
  lineinfile:
    dest=/etc/apt/sources.list
    line="deb http://cran.rstudio.com/bin/linux/ubuntu trusty/"  #"

- name: Add Cloudera's apt key
  apt_key: url=http://archive.cloudera.com/cdh5/ubuntu/trusty/amd64/cdh/archive.key

- name: Add R apt key
  command: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9

- name: Update APT cache
  apt: update_cache=yes

- name: Install CloudMan-required system packages
  apt: pkg={{ item }} state=latest
  with_items:
    - ansible
    - automake  # s3fs required
    - build-essential  # s3fs required
    - cloudera-manager-daemons  # Cloudera Manager
    - cloudera-manager-server  # Cloudera Manager
    - cloudera-manager-agent  # Cloudera Manager
    - fail2ban
    - fuse
    - glusterfs-client
    - jsvc  # Cloudgene required
    - libcurl4-openssl-dev  # s3fs required
    - libfuse-dev  # s3fs required
    - libfuse2
    - libmysql-java  # Cloudera Manager required
    - libpcre3-dev
    - libreadline6-dev
    - libslurm-dev
    - libssl-dev
    - libtool  # s3fs required
    - libxml2-dev  # s3fs required
    - libmunge-dev
    - mime-support  # s3fs required
    - munge
    - nfs-common
    - nfs-kernel-server
    - nodejs-legacy  # for IPython Interactive Environment
    - npm  # for IPython Interactive Environment
    - ntp  # Cloudera Manager required
    - nginx-extras
    - pkg-config
    - postgresql-server-dev-9.3
    - python-pip
    - python-tk  # for IPython %cpaste magic function
    - python-yaml
    - rabbitmq-server
    - screen
    - slurm-llnl
    - uwsgi
    - uwsgi-plugin-python
    - xfsprogs

- name: Install new r-base 3.2.2 or above
  apt: name=r-base=3.2* state=present

- name: Upgrade system packages
  apt: upgrade=yes
